(function(){
const KEY='ourDealRunner.v1';
const emptyDeal=()=>({query:'',address:'',city:'Orlando',state:'Florida',zip:'',source:'',beds:'',baths:'',sqft:'',year:'',asking:'',notes:'',agentName:'',agentPhone:'',agentEmail:'',arvOverride:'',repairs:'35000',buffer:'YES',buybox:'70',fee:'12000',structure:'Assignment',earnest:'1000',marketing:'250',contractActual:'',buyerActual:'',comps:[],lookupNote:''});
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');return{deal:Object.assign(emptyDeal(),raw.deal||{}),buyers:raw.buyers||[],pipeline:raw.pipeline||[],settings:Object.assign({rentcastKey:'',fed:'22',se:'YES'},raw.settings||{})};}catch(e){return{deal:emptyDeal(),buyers:[],pipeline:[],settings:{rentcastKey:'',fed:'22',se:'YES'}};}}
let store=load();
const $=id=>document.getElementById(id);
const money=n=>isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}):'\u2014';
const num=v=>{const n=parseFloat(String(v).replace(/[^0-9.]/g,''));return isFinite(n)?n:0;};
const stateObj=name=>(window.OUR_STATES||[]).find(s=>s.name===name)||{name,abbr:'\u2014',rate:0,posture:'Check',hint:''};
const save=()=>localStorage.setItem(KEY,JSON.stringify(store));
function show(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id==='view-'+view));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render();}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
function bind(id,key){const el=$(id);if(!el)return;el.addEventListener('input',()=>{store.deal[key]=el.value;save();if(key==='state')$('statePill').textContent=stateObj(el.value).abbr;paint();});el.addEventListener('change',()=>{store.deal[key]=el.value;save();render();});}
function fillStates(){const sel=$('f_state');if(sel)sel.innerHTML=(window.OUR_STATES||[]).map(s=>`<option value="${s.name}">${s.name}</option>`).join('');}
function setv(id,v){if($(id))$(id).value=v||'';}
function paintHouse(){const d=store.deal;setv('f_address',d.address);setv('f_city',d.city);setv('f_state',d.state||'Florida');setv('f_zip',d.zip);setv('f_source',d.source);setv('f_beds',d.beds);setv('f_baths',d.baths);setv('f_sqft',d.sqft);setv('f_year',d.year);setv('f_asking',d.asking);setv('f_notes',d.notes);setv('f_agentName',d.agentName);setv('f_agentPhone',d.agentPhone);setv('f_agentEmail',d.agentEmail);if($('statePill'))$('statePill').textContent=stateObj(d.state).abbr;}
function paintNums(){const d=store.deal;setv('n_arv',d.arvOverride);setv('n_repairs',d.repairs);setv('n_buffer',d.buffer||'YES');setv('n_buybox',d.buybox||'70');setv('n_fee',d.fee);setv('n_structure',d.structure||'Assignment');setv('n_earnest',d.earnest);setv('n_marketing',d.marketing);setv('n_contract',d.contractActual);setv('n_buyer',d.buyerActual);setv('s_key',store.settings.rentcastKey);setv('s_fed',store.settings.fed||'22');setv('s_se',store.settings.se||'YES');}
function compARV(){const sq=num(store.deal.sqft)||1450;const comps=(store.deal.comps||[]).filter(c=>num(c.price)>0&&num(c.sqft)>0);if(!comps.length)return{arv:0,psf:0,count:0};let wSum=0,wPsf=0;comps.forEach(c=>{const dist=num(c.miles)||1,cond=num(c.condition)||3,gap=Math.min(0.4,Math.abs(num(c.sqft)-sq)/sq),w=Math.max(0.1,(1/(1+dist))*(cond/5)*(1-gap));wSum+=w;wPsf+=w*(num(c.price)/num(c.sqft));});const psf=wSum?wPsf/wSum:0;return{arv:psf*sq,psf,count:comps.length};}
function calc(){const d=store.deal,st=stateObj(d.state),from=compARV(),arv=num(d.arvOverride)||from.arv||0,repairs=d.buffer==='NO'?num(d.repairs):num(d.repairs)*1.1,bb=(num(d.buybox)||70)/100,fee=num(d.fee),mao=arv*bb-repairs,rec=Math.max(0,mao-fee),contract=num(d.contractActual)||rec,buyer=num(d.buyerActual)||mao,gross=buyer-contract,extra=d.structure==='Double Close'?4500:500,pretax=gross-num(d.marketing)-extra,fed=(num(store.settings.fed)||22)/100,se=store.settings.se==='YES'?0.153:0,tax=Math.max(0,pretax)*(fed+se+(st.rate||0));return{arv,from,repairs,mao,rec,contract,buyer,gross,extra,pretax,tax,net:pretax-tax,st};}
const attr=v=>String(v==null?'':v).replace(/"/g,'"');
const esc=v=>String(v==null?'':v).replace(/[&<>]/g,s=>({'&':'&','<':'<','>':'>'}[s]));
function paintPeople(c){const d=store.deal;if($('realtorCard')){const has=d.agentName||d.agentPhone||d.agentEmail;$('realtorCard').innerHTML=has?`<p><strong>${esc(d.agentName||'Listing agent')}</strong></p><p class="muted">${esc(d.agentPhone||'No phone on the listing')}</p>${d.agentPhone?`<a class="btn btn-primary" href="tel:${encodeURIComponent(d.agentPhone)}">Call realtor</a>`:''}`:`<p class="muted">No realtor on this listing yet.</p>`;}if($('buyerList'))$('buyerList').innerHTML=(store.buyers||[]).map((b,i)=>`<div class="person-row"><input data-buyer="${i}" data-k="name" placeholder="Buyer" value="${attr(b.name)}"/><div class="row"><input data-buyer="${i}" data-k="phone" placeholder="Phone" value="${attr(b.phone)}"/><input data-buyer="${i}" data-k="email" placeholder="Email" value="${attr(b.email)}"/></div><button class="btn btn-ghost" data-delbuyer="${i}">Remove</button></div>`).join('');if($('buyerMatches')&&!(store.buyers||[]).length)$('buyerMatches').innerHTML='<p class="muted">No saved buyers yet.</p>';if($('scriptAgent'))$('scriptAgent').textContent='Hi, this is [YOUR NAME]. I am looking at '+(d.address||'the house')+' in '+(d.city||'')+'. I work with cash and as-is buyers. The listing is at '+money(num(d.asking))+'. If they will look at a cash as-is number, I can move fast.';if($('scriptBuyer'))$('scriptBuyer').textContent='Hi, this is [YOUR NAME]. I have '+ (d.address||'a house')+' in '+(d.city||'')+' under review. Do you have a cash buyer for an as-is 2/1?';}
function paintComps(){const list=$('compList');if(!list)return;const comps=store.deal.comps||[];if(!comps.length){list.innerHTML='<p class="muted">No comps yet.</p>';return;}list.innerHTML=comps.map((c,i)=>`<div class="comp-row"><input data-comp="${i}" data-k="address" placeholder="Address" value="${attr(c.address)}"/><div class="row3"><input data-comp="${i}" data-k="price" placeholder="Price" value="${attr(c.price)}"/><input data-comp="${i}" data-k="sqft" placeholder="Sqft" value="${attr(c.sqft)}"/><input data-comp="${i}" data-k="miles" placeholder="Miles" value="${attr(c.miles)}"/></div><button class="btn btn-ghost" data-delcomp="${i}">Remove</button></div>`).join('');}
function paintPipe(){const list=$('pipeList');if(!list)return;if(!store.pipeline.length){list.innerHTML='<p class="muted">No saved deals yet.</p>';return;}list.innerHTML=store.pipeline.slice().reverse().map((p,idx)=>{const real=store.pipeline.length-1-idx;return `<div class="pipe-row"><strong>${esc(p.address||'Untitled')}</strong><div class="tiny">${esc(p.city||'')} \u00b7 ${money(p.contract||0)}</div><div class="btn-row"><button class="btn btn-ghost" data-openpipe="${real}">Open</button><button class="btn btn-ghost" data-delpipe="${real}">Delete</button></div></div>`;}).join('');}
function paint(){const c=calc(),d=store.deal,pc=/License|Registration/.test(c.st.posture)?'danger':c.st.posture==='Friendly'?'info':'caution';if($('houseBanner'))$('houseBanner').innerHTML=`<div class="banner ${pc}">${c.st.name}: ${c.st.posture}. ${c.st.hint}.</div>`;if($('houseKpis'))$('houseKpis').innerHTML=`<div class="kpi"><span>Asking</span><strong>${money(num(d.asking))}</strong></div><div class="kpi"><span>ARV</span><strong>${money(c.arv)}</strong></div><div class="kpi"><span>Contract</span><strong class="good">${money(c.contract)}</strong></div><div class="kpi"><span>Net</span><strong>${money(c.net)}</strong></div>`;if($('compKpis'))$('compKpis').innerHTML=`<div class="kpi"><span>Comps</span><strong>${c.from.count}</strong></div><div class="kpi"><span>Comp ARV</span><strong>${money(c.from.arv)}</strong></div>`;if($('numKpis'))$('numKpis').innerHTML=`<div class="kpi"><span>Contract</span><strong class="good">${money(c.contract)}</strong></div><div class="kpi"><span>Gross</span><strong>${money(c.gross)}</strong></div><div class="kpi"><span>Net</span><strong>${money(c.net)}</strong></div><div class="kpi"><span>Works?</span><strong class="${c.contract>0?'good':'bad'}">${c.contract>0?'Yes':'No'}</strong></div>`;if($('numBreakdown'))$('numBreakdown').innerHTML=`<h3>How we got there</h3><table class="sheet"><tr><td>ARV</td><td>${money(c.arv)}</td></tr><tr><td>Repairs</td><td>${money(c.repairs)}</td></tr><tr><td>Buyer max</td><td>${money(c.mao)}</td></tr><tr><td>Contract</td><td>${money(c.rec)}</td></tr></table>`;if($('paperFields'))$('paperFields').textContent='[PROPERTY_ADDRESS]  '+(d.address||'')+'\n[CITY]  '+(d.city||'')+'\n[STATE]  '+(d.state||'')+'\n[ZIP]  '+(d.zip||'')+'\n[PURCHASE_PRICE]  '+Math.round(c.contract)+'\n[ASSIGNMENT_FEE]  '+Math.round(num(d.fee)||c.gross);paintPeople(c);if($('runTicker'))$('runTicker').textContent=money(c.contract);if($('numTicker'))$('numTicker').textContent=money(c.contract);if($('listingTitle'))$('listingTitle').textContent=d.address||'No house loaded';if($('listingSub'))$('listingSub').textContent=[d.city,stateObj(d.state).abbr,d.zip].filter(Boolean).join(' \u00b7 ')||'Paste a link on Run';if($('lblBuybox'))$('lblBuybox').textContent=(d.buybox||'70')+'%';if($('lblFee'))$('lblFee').textContent=money(num(d.fee));if($('lblRepairs'))$('lblRepairs').textContent=money(num(d.repairs));if($('s_buybox'))$('s_buybox').value=String(num(d.buybox)||70);if($('s_fee'))$('s_fee').value=String(num(d.fee)||12000);if($('s_repairs'))$('s_repairs').value=String(num(d.repairs)||0);const maxB=Math.max(c.arv,1);if($('dealStack'))$('dealStack').innerHTML=[['ARV','arv',c.arv],['Buyer max','mao',Math.max(c.mao,0)],['Contract','con',Math.max(c.contract,0)],['Net','net',Math.max(c.net,0)]].map(([l,cl,v])=>`<div class="bar-wrap"><span>${l}</span><div class="bar ${cl}"><i style="width:${Math.min(100,(v/maxB)*100)}%"></i></div><span>${money(v)}</span></div>`).join('');}
function render(){paintHouse();paintNums();paintComps();paintPipe();paint();}
fillStates();
[['f_address','address'],['f_city','city'],['f_state','state'],['f_zip','zip'],['f_source','source'],['f_beds','beds'],['f_baths','baths'],['f_sqft','sqft'],['f_year','year'],['f_asking','asking'],['f_notes','notes'],['f_agentName','agentName'],['f_agentPhone','agentPhone'],['f_agentEmail','agentEmail'],['n_arv','arvOverride'],['n_repairs','repairs'],['n_buffer','buffer'],['n_buybox','buybox'],['n_fee','fee'],['n_structure','structure'],['n_earnest','earnest'],['n_marketing','marketing'],['n_contract','contractActual'],['n_buyer','buyerActual']].forEach(([id,k])=>bind(id,k));
function slider(id,key,sync){const el=$(id);if(!el)return;el.addEventListener('input',()=>{store.deal[key]=el.value;if(sync&&$(sync))$(sync).value=el.value;save();paint();});}
slider('s_buybox','buybox','n_buybox');slider('s_fee','fee','n_fee');slider('s_repairs','repairs','n_repairs');
if($('s_key'))$('s_key').addEventListener('change',()=>{store.settings.rentcastKey=$('s_key').value.trim();save();});
if($('s_fed'))$('s_fed').addEventListener('input',()=>{store.settings.fed=$('s_fed').value;save();paint();});
if($('s_se'))$('s_se').addEventListener('change',()=>{store.settings.se=$('s_se').value;save();paint();});
document.body.addEventListener('input',e=>{if(e.target.dataset.comp!=null){store.deal.comps[Number(e.target.dataset.comp)][e.target.dataset.k]=e.target.value;save();paint();}if(e.target.dataset.buyer!=null){store.buyers[Number(e.target.dataset.buyer)][e.target.dataset.k]=e.target.value;save();}});
document.body.addEventListener('click',e=>{if(e.target.dataset.delcomp!=null){store.deal.comps.splice(Number(e.target.dataset.delcomp),1);save();render();}if(e.target.dataset.delbuyer!=null){store.buyers.splice(Number(e.target.dataset.delbuyer),1);save();render();}if(e.target.dataset.delpipe!=null){store.pipeline.splice(Number(e.target.dataset.delpipe),1);save();render();}if(e.target.dataset.openpipe!=null){store.deal=Object.assign(emptyDeal(),store.pipeline[Number(e.target.dataset.openpipe)].deal||store.pipeline[Number(e.target.dataset.openpipe)]);save();show('house');}});
if($('btnAddComp'))$('btnAddComp').addEventListener('click',()=>{store.deal.comps.push({address:'',price:'',sqft:'',miles:'',condition:'3',soldOn:''});save();render();});
if($('btnAddBuyer'))$('btnAddBuyer').addEventListener('click',()=>{store.buyers.push({name:'',phone:'',email:'',markets:'Miami-Dade',maxPrice:''});save();render();});
if($('btnSaveDeal'))$('btnSaveDeal').addEventListener('click',()=>{const c=calc();store.pipeline.push({address:store.deal.address,city:store.deal.city,state:store.deal.state,contract:c.contract,deal:JSON.parse(JSON.stringify(store.deal))});save();render();if($('runStatus'))$('runStatus').textContent='Saved.';});
if($('btnCopyFields'))$('btnCopyFields').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('paperFields').textContent);}catch(e){}});
if($('chipSample'))$('chipSample').addEventListener('click',()=>$('btnDemo')&&$('btnDemo').click());
if($('chipLink'))$('chipLink').addEventListener('click',()=>{$('chipLink').classList.add('on');$('chipAddr').classList.remove('on');});
if($('chipAddr'))$('chipAddr').addEventListener('click',()=>{$('chipAddr').classList.add('on');$('chipLink').classList.remove('on');});
if($('btnDemo'))$('btnDemo').addEventListener('click',()=>{store.deal=Object.assign(emptyDeal(),{query:'123 Example Ave, Orlando, FL 32801',address:'123 Example Ave',city:'Orlando',state:'Florida',zip:'32801',beds:'3',baths:'2',sqft:'1450',asking:'189000',repairs:'35000',comps:[{address:'110 Pine St',price:'275000',sqft:'1480',miles:'0.4',condition:'4'},{address:'88 Oak Ave',price:'268000',sqft:'1390',miles:'0.6',condition:'3'}]});if($('query'))$('query').value=store.deal.query;save();show('numbers');});
function parseListing(q){const url=(q.match(/https?:\/\/\S+/i)||[''])[0];const out={source:url||'',address:'',city:'',state:'',zip:''};const slug=((url||q).match(/homedetails\/([^/]+)/i)||[])[1];if(slug){const bits=decodeURIComponent(slug).split('-').filter(Boolean);const zip=bits.pop()||'';const st=(bits.pop()||'').toUpperCase();const suf=['St','Ave','Blvd','Ln','Dr','Ct','Rd','Way','Pl','Cir','Ter','Hwy','Pkwy','Trail','Loop','Street','Avenue','Lane','Drive','Court','Place','Terrace'];let cut=Math.max(0,bits.length-2);for(let i=0;i<bits.length;i++)if(suf.includes(bits[i]))cut=i;out.address=bits.slice(0,cut+1).join(' ');out.city=bits.slice(cut+1).join(' ');out.zip=/^\d{5}$/.test(zip)?zip:'';const map={AL:'Alabama',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',FL:'Florida',GA:'Georgia',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',MD:'Maryland',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',NV:'Nevada',NJ:'New Jersey',NY:'New York',NC:'North Carolina',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',SC:'South Carolina',TN:'Tennessee',TX:'Texas',UT:'Utah',VA:'Virginia',WA:'Washington',WI:'Wisconsin'};out.state=map[st]||'';}else{const parts=q.replace(url,'').split(',').map(x=>x.trim()).filter(Boolean);if(parts[0])out.address=parts[0];if(parts[1])out.city=parts[1];}return out;}
if($('btnRun'))$('btnRun').addEventListener('click',()=>{const q=(($('query')&&$('query').value)||'').trim();if(!q){$('runStatus').textContent='Paste a link or address first.';return;}store.deal.query=q;const p=parseListing(q);if(p.source)store.deal.source=p.source;if(p.address)store.deal.address=p.address;if(p.city)store.deal.city=p.city;if(p.state)store.deal.state=p.state;if(p.zip)store.deal.zip=p.zip;save();$('runStatus').textContent=p.address?(p.address+', '+(p.city||'')+' loaded. Send this link in chat for comps and price.'):'Link saved. Send it in chat so I can fill comps.';show('house');});
if($('btnImport'))$('btnImport').addEventListener('click',()=>$('importBox')&&$('importBox').scrollIntoView({behavior:'smooth'}));
if($('btnApplyImport'))$('btnApplyImport').addEventListener('click',()=>{try{const data=JSON.parse($('importBox').value.trim());['address','city','state','zip','source','beds','baths','sqft','year','asking','notes','agentName','agentPhone','agentEmail','arvOverride','repairs'].forEach(k=>{if(data[k]!=null)store.deal[k]=String(data[k]);});if(Array.isArray(data.comps))store.deal.comps=data.comps;save();show('numbers');}catch(e){$('runStatus').textContent='Not valid JSON.';}});
if($('btnLoad5612'))$('btnLoad5612').addEventListener('click',()=>{store.deal=Object.assign(emptyDeal(),{query:'https://www.zillow.com/homedetails/1300-Bruce-St-Augusta-GA-30901/14959467_zpid/',address:'1300 Bruce St',city:'Augusta',state:'Georgia',zip:'30901',source:'https://www.zillow.com/homedetails/1300-Bruce-St-Augusta-GA-30901/14959467_zpid/',beds:'2',baths:'1',sqft:'936',year:'1955',asking:'50000',notes:'As-is investor special. Full rehab. 0.37 acre.',arvOverride:'120000',repairs:'40000',fee:'8000',comps:[{address:'1304 Bruce St sold',price:'50000',sqft:'1326',miles:'0.02',condition:'2'},{address:'1326 Bruce St sold',price:'50000',sqft:'696',miles:'0.1',condition:'2'}]});if($('query'))$('query').value=store.deal.query;save();show('house');});
async function copyId(id,btn){try{await navigator.clipboard.writeText($(id).textContent);btn.textContent='Copied';}catch(e){}}
if($('btnCopyAgent'))$('btnCopyAgent').addEventListener('click',()=>copyId('scriptAgent',$('btnCopyAgent')));
if($('btnCopyBuyer'))$('btnCopyBuyer').addEventListener('click',()=>copyId('scriptBuyer',$('btnCopyBuyer')));
if($('query'))$('query').value=store.deal.query||'';
render();
})();
