window.OUR_STATES = [
  { name: "Alabama", abbr: "AL", rate: 0.05, posture: "Disclosure", hint: "Assignment" },
  { name: "Alaska", abbr: "AK", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "Arizona", abbr: "AZ", rate: 0.025, posture: "Disclosure", hint: "Assignment" },
  { name: "Arkansas", abbr: "AR", rate: 0.039, posture: "Friendly", hint: "Assignment" },
  { name: "California", abbr: "CA", rate: 0.133, posture: "Caution", hint: "Assignment first" },
  { name: "Colorado", abbr: "CO", rate: 0.044, posture: "Disclosure", hint: "Assignment" },
  { name: "Connecticut", abbr: "CT", rate: 0.0699, posture: "Registration", hint: "Pause / register" },
  { name: "Delaware", abbr: "DE", rate: 0.066, posture: "Caution", hint: "Assignment" },
  { name: "District of Columbia", abbr: "DC", rate: 0.1075, posture: "Caution", hint: "Assignment" },
  { name: "Florida", abbr: "FL", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "Georgia", abbr: "GA", rate: 0.0539, posture: "Friendly", hint: "Assignment" },
  { name: "Hawaii", abbr: "HI", rate: 0.11, posture: "Caution", hint: "Assignment" },
  { name: "Idaho", abbr: "ID", rate: 0.05695, posture: "Friendly", hint: "Assignment" },
  { name: "Illinois", abbr: "IL", rate: 0.0495, posture: "License", hint: "License or double close" },
  { name: "Indiana", abbr: "IN", rate: 0.0305, posture: "Friendly", hint: "Assignment" },
  { name: "Iowa", abbr: "IA", rate: 0.038, posture: "Friendly", hint: "Assignment" },
  { name: "Kansas", abbr: "KS", rate: 0.057, posture: "Disclosure", hint: "Assignment" },
  { name: "Kentucky", abbr: "KY", rate: 0.04, posture: "License", hint: "License first" },
  { name: "Louisiana", abbr: "LA", rate: 0.0425, posture: "Friendly", hint: "Assignment" },
  { name: "Maine", abbr: "ME", rate: 0.0715, posture: "Friendly", hint: "Assignment" },
  { name: "Maryland", abbr: "MD", rate: 0.0575, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Massachusetts", abbr: "MA", rate: 0.05, posture: "Caution", hint: "Assignment" },
  { name: "Michigan", abbr: "MI", rate: 0.0425, posture: "Friendly", hint: "Assignment" },
  { name: "Minnesota", abbr: "MN", rate: 0.0985, posture: "Caution", hint: "Assignment" },
  { name: "Mississippi", abbr: "MS", rate: 0.047, posture: "Friendly", hint: "Assignment" },
  { name: "Missouri", abbr: "MO", rate: 0.048, posture: "Friendly", hint: "Assignment" },
  { name: "Montana", abbr: "MT", rate: 0.059, posture: "Friendly", hint: "Assignment" },
  { name: "Nebraska", abbr: "NE", rate: 0.0584, posture: "Caution", hint: "Assignment" },
  { name: "Nevada", abbr: "NV", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "New Hampshire", abbr: "NH", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "New Jersey", abbr: "NJ", rate: 0.1075, posture: "Caution", hint: "Assignment" },
  { name: "New Mexico", abbr: "NM", rate: 0.059, posture: "Friendly", hint: "Assignment" },
  { name: "New York", abbr: "NY", rate: 0.109, posture: "Caution", hint: "Assignment / local counsel" },
  { name: "North Carolina", abbr: "NC", rate: 0.0425, posture: "License", hint: "License first" },
  { name: "North Dakota", abbr: "ND", rate: 0.025, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Ohio", abbr: "OH", rate: 0.035, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Oklahoma", abbr: "OK", rate: 0.0475, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Oregon", abbr: "OR", rate: 0.099, posture: "Registration", hint: "Register first" },
  { name: "Pennsylvania", abbr: "PA", rate: 0.0307, posture: "License", hint: "License / local counsel" },
  { name: "Rhode Island", abbr: "RI", rate: 0.0599, posture: "Caution", hint: "Assignment" },
  { name: "South Carolina", abbr: "SC", rate: 0.062, posture: "License", hint: "Private assignment / license" },
  { name: "South Dakota", abbr: "SD", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "Tennessee", abbr: "TN", rate: 0, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Texas", abbr: "TX", rate: 0, posture: "Friendly", hint: "Assignment" },
  { name: "Utah", abbr: "UT", rate: 0.0455, posture: "Friendly", hint: "Assignment" },
  { name: "Vermont", abbr: "VT", rate: 0.0875, posture: "Caution", hint: "Assignment" },
  { name: "Virginia", abbr: "VA", rate: 0.0575, posture: "Disclosure", hint: "Assignment" },
  { name: "Washington", abbr: "WA", rate: 0, posture: "Caution", hint: "Assignment" },
  { name: "West Virginia", abbr: "WV", rate: 0.0512, posture: "Friendly", hint: "Assignment" },
  { name: "Wisconsin", abbr: "WI", rate: 0.0765, posture: "Disclosure", hint: "Assignment + disclosure" },
  { name: "Wyoming", abbr: "WY", rate: 0, posture: "Friendly", hint: "Assignment" }
];
